export const cards = [
  {
    id: 1,
    idSelector: "inde-two",
    btype: "Weekly",
    totrem: "$565",
    itemone: "Gas: $45",
    itemtwo: "Groceries: $60",
    itemthree: "Pet Care/Food: $27",
    itemfour: "Personal Care: $25",
  },
  {
    id: 2,
    idSelector: "inde-one",
    btype: "Monthly",
    totrem: "$2,250",
    itemone: "Rent: $850",
    itemtwo: "Groceries: $250",
    itemthree: "Entertainment: $200",
    itemfour: "Insurance: $450",
  },
  {
    id: 3,
    idSelector: "inde-three",
    btype: "Yearly",
    totrem: "$27,000",
    itemone: "Rent: $10,200",
    itemtwo: "Car Loan: $6,186",
    itemthree: "Vacation: $2,400",
    itemfour: "Subscriptions: $350",
  },
];
